### ISSUE TITLE
Difference between weights files

### ISSUE THREAD

**Issue by vukasin-stanojevic** [MCG-NJU/MixSort#17]
Hello,
What is the difference between yolox_x_sports_mix.pth.tar and yolox_x_sports_train.pth.tar files, i.e. when to use which file?

Best regards!

**Comment by ret-1** [comment]
Hello @vukasin-stanojevic ,

For `yolox_x_sports_mix.pth.tar`, data in train and validation set are used. For `yolox_x_sports_train.pth.tar`, only data in train set is used.

 You could refer to the experiment part of our thesis.
