### ISSUE TITLE
Add better instructions for TrackEval

### ISSUE THREAD

**Issue by tteresi7** [MCG-NJU/MixSort#3]
If possible, could we get a modified `TrackEval`, some sort of custom evaluator with some documentation, or just a guide on adding SportsMOT to `TrackEval`?  Pointing to to the `TrackEval` repository isn't very helpful when `TrackEval` isn't set up for SportsMOT and needs custom information to run, and their documentation is a bit lacking when it comes to this.

**Comment by ret-1** [comment]
@tteresi7, Thank you for raising this concern. To address this, I've integrated `TrackEval` as a submodule within our repository. This should provide a more streamlined experience. I've also updated the `README.md` with instructions on how to use the integrated submodule. You can find these changes in #5.

However, I haven't merged the PR yet as I wanted to ensure thorough testing. I'd greatly appreciate it if you could review the PR and provide any feedback or suggestions.

**Comment by ret-1** [comment]
Merged #5 .
