### ISSUE TITLE
Error When Loading Pretrained Model

### ISSUE THREAD

**Issue by wanghao14** [MCG-NJU/MixSort#7]
Hi, thanks for open-sourcing your solid work! I attempted to load your pretrained model by `torch.load('MixFormer_dance_train.pth.tar', map_location='cpu')` but encountered the following error:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/conda/envs/MixSort/lib/python3.8/site-packages/torch/serialization.py", line 712, in load
>     return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>   File "/opt/conda/envs/MixSort/lib/python3.8/site-packages/torch/serialization.py", line 1046, in _load
>     result = unpickler.load()
>   File "/opt/conda/envs/MixSort/lib/python3.8/site-packages/torch/serialization.py", line 1039, in find_class
>     return super().find_class(mod_name, name)
> ModuleNotFoundError: No module named 'lib'

Maybe you can reproduce this error by creating a new Conda environment and installing the dependencies according to the installation instructions [your guidance](https://github.com/MCG-NJU/MixSort#installation). Looking forward to your reply.

**Comment by ret-1** [comment]
Hello @wanghao14 ,
You could solve this by running the following before `torch.load()`:
```python
import sys
sys.path.append('<MixSort_HOME>/MixViT')
```
Note: In our entry scripts, we have similar step:
https://github.com/MCG-NJU/MixSort/blob/a078f5bf6ae9fbeecbc1384479d5f02ab8b9e7f6/tools/track_mixsort.py#L7

**Comment by wanghao14** [comment]
Hi @ret-1,

Thanks for your timely reply and my problem is addressed.
